### ISSUE TITLE
Off-by-one error in fetch_results pagination handler

### ISSUE THREAD

**Issue by GregSutcliffe** [rladies/meetupr#111]
I'm testing the latest version MeetupR for use in my Ansible stats. Ansible has a large number of meetups - `find_groups` reports downloading 324 entries, so I was surprised to get an object with 400 entries in it.

Reproducer:
```
> groups <- find_groups('Ansible')
Downloading 324 record(s)...
> dim(groups)
[1] 400  21
```
So, my suspicions were raised. I dug into the call stack, and ended up [here](https://github.com/rladies/meetupr/blob/c9c584335377966c7c9e08534089f84d921cff50/R/internals.R#L96-L113). It would appear that the `for i in ....` loop is duplicating the first page and ignoring the second. Here's a marginally hacked-up reproducer of the issue from inside `.fetch_results`:

```
# faked up call to meetupr:::.fetch_results('find/groups',text='Ansible',radius='global',verbose=T)

api_path = 'find/groups'
text = 'Ansible'
radius = 'global'
verbose = T
event_status = NULL

res <- meetupr:::meetup_call(api_path = api_path, event_status = event_status, 
                             offset = 0, verbose = verbose, text = text, radius = radius)

total_records <- as.integer(res$headers$`x-total-count`)
if (length(total_records) == 0) 
  total_records <- 1L
records <- res$result
if (total_records == 0) {
  return(res$result)
}
if (verbose) 
  cat("Downloading", total_records, "record(s)...\n", sep = " ")
if ((length(records) < total_records) & !is.null(res$headers$link)) {
  offsetn <- ceiling(total_records/length(records))
  all_records <- list(records)
  for (i in 1:(offsetn - 1)) {
    res <- meetupr:::meetup_call(api_path = api_path, event_status = event_status, 
                                 offset = i, text = text, radius = radius, verbose = verbose)
    next_url <- strsplit(strsplit(res$headers$link, split = "<")[[1]][2], 
                         split = ">")[[1]][1]
    next_url <- gsub(meetupr:::meetup_api_prefix(), "", next_url)
    res <- meetupr:::meetup_call(next_url, event_status)
    all_records[[i + 1]] <- res$result
  }
  records <- unlist(all_records, recursive = FALSE)
}
identical(all_records[[1]], all_records[[2]])
```
```
Downloading 324 record(s)...
[1] TRUE
```

I'm trying to understand exactly where the issue is with the loop. If I figure it out, I'll send a PR, but if someone beats me to it, thats fine too ;)

**Comment by GregSutcliffe** [comment]
OK, that was less hard than I thought, but perhaps I'm missing something?

The issue appears to be that the code overwrites `res`. At this point in the above repro, all is fine:

```
i=1
res <- meetupr:::meetup_call(api_path = api_path, event_status = event_status, 
                                  offset = i, text = text, radius = radius, verbose = verbose)
length(res$result)
[1] 124
```
But 3 lines later, having parsed the "next_url" from the response, it gets reset:

```
next_url <- strsplit(strsplit(res$headers$link, split = "<")[[1]][2], 
                         split = ">")[[1]][1]
next_url <- gsub(meetupr:::meetup_api_prefix(), "", next_url)
res <- meetupr:::meetup_call(next_url, event_status)
length(res$result)
[1] 200
```

I'm unclear on why we need to parse `next_url` at all? We have `i = 1:offsetn - 1` which gives us the direct URLs anyway. Can't we use:

```
  for (i in 1:(offsetn - 1)) {
    res <- meetupr:::meetup_call(api_path = api_path, event_status = event_status, 
                                 offset = i, text = text, radius = radius, verbose = verbose)
    all_records[[i + 1]] <- res$result
  }
```
and be done? This seems to work:

```
length(records)
[1] 324
```

Thoughts? Happy to send a PR for this, but I'm not sure if I'm missing a case where next_url is needed?

**Comment by GregSutcliffe** [comment]
Went for a walk to think a bit more about it, and realised that if Meetup provides a next URL, we should probably use it. Since we already have `res` defined for the first page of results outside the loop, we can just omit the first call to `res <- ...` and parse/use the `next_url`. Like this:

```
    for (i in 1:(offsetn - 1)) {
#      res <- meetup_call(api_path = api_path, event_status = event_status, 
#                         offset = i, ...)
      next_url <- strsplit(strsplit(res$headers$link, split = "<")[[1]][2], 
                           split = ">")[[1]][1]
      next_url <- gsub(meetupr:::meetup_api_prefix(), "", next_url)
      res <- meetupr:::meetup_call(next_url, event_status)
      all_records[[i + 1]] <- res$result
    }
```
I wanted to make sure that worked for more than two pages, so I found a search with > 400 groups:
```
groups <- my_find_groups('London Pub')
Downloading 410 record(s)...
> distinct(groups,urlname) %>% nrow()
[1] 410
```
Seems good?

**Comment by ledell** [comment]
@GregSutcliffe Thanks for the report!  

It looks like a number of people have worked on that loop over the years, so its possible it used to work and was recently broken (we don't have enough tests).  I'm wondering if it's caused by this [commit](https://github.com/rladies/meetupr/commit/e0022797226c5a2bed0d90e3b74390efbba6cb2d), which was actually meant to fix a bug from [this commit](https://github.com/rladies/meetupr/commit/036ce4141a8400a7ace134faa9ec90d481c77cc9), but perhaps it didn't or maybe introduced a new one. When I first wrote it, I don't think meetup provided the next URL, which is why I did it that way.  I am in support of using your solution!

I opened an [issue](https://github.com/rladies/meetupr/issues/112) to document the missing test as well.

**Comment by GregSutcliffe** [comment]
Thanks for the feedback @ledell. Just for interest, I ran a `git bisect` across the tree (which was a bit prickly because some of the commits occur before the OAuth change making them ... challenging to test :P)

As far as I can tell, this is the bad change: https://github.com/rladies/meetupr/commit/0916f4436fa1ab8f01a3c7d50ff65a5accfdd162#diff-3f3bff8ab673bfcf61e7b8159249c3a14e19f9916656ed1db4114ec2efd2949aR89 - you can see the extra call to quick fetch creeping in which is resulting in the duplicate data. I suspect most people aren't hitting this because they only get data that fits inside Meetup's rather generous 200-item pagination limit. EDIT actually the old code seems to work for my "London Pub" example - perhaps this is a special case where `offsetn == 2`...

I'll get a PR in for the change now, and maybe see if I can write a test for it. Mocking a large enough reply is the issue I guess...

**Comment by drmowinckels** [comment]
.fetch_result is obsolete as the new Meetup API. And the new API doesnt seem to have pagination issues (I've not seen it yet). So I think this issue can be closed.
