### ISSUE TITLE
Add missing LICENSE.md file

### ISSUE THREAD

**Issue by ledell** [rladies/meetupr#117]
According to [this](https://r-pkgs.org/license.html#key-files), we are supposed to have a copy of the MIT license included in a `LICENSE.md` file.  The `LICENSE` file is only used to identify which license is being used and who owns the copyright, but does not include the actual text from the MIT license. We are currently missing this file, so let's add it.   We also need to add to to `.Rbuildignore` per CRAN requirements (we are not on CRAN currently but we might be at some point).

The reference above also says this (so I wonder if this is out of date):

> A name of a license “template” and a file containing specific variables. The most common case is MIT + file LICENSE, where the LICENSE file needs to contain two fields: the year and copyright holder.

However, Github does not use this two-liner format anymore and in order for the type of license to show up in the Github repo UI and for people to know what license is being used easily, it has a slightly longer format than the old two-liner, which I have already updated [here](https://github.com/rladies/meetupr/blob/master/LICENSE).

**Comment by maelle** [comment]
`usethis::use_mit_license()` might help.

**Comment by drmowinckels** [comment]
This seems resolved now, right? Everything looks ok on my end at least.

**Comment by maelle** [comment]
No LICENCE.md though?
