### ISSUE TITLE
Add GraphQL support

### ISSUE THREAD

**Issue by ledell** [rladies/meetupr#118]
Meetup will be deprecating the REST API and replacing it with GraphQL.  The REST API will be deprecated at the end of 2021, and the GraphQL API is already active.  Therefore, for this package to remain usable, we have to replace the guts.  The [ghql](https://github.com/ropensci/ghql) package could be useful.

Here’s the info on migrating from REST to GraphQL: https://www.meetup.com/api/migrating
More info about GraphQL: https://www.meetup.com/api/general

FYI: @GregSutcliffe @maelle @benubah @LucyMcGowan @cvitolo @jennybc @Athanasiamo @olgamie @RickPack @malcolmbarrett @brooklynbagel @hfrick

**Comment by ledell** [comment]
@GregSutcliffe @maelle @benubah @LucyMcGowan @cvitolo @jennybc @Athanasiamo @olgamie @RickPack @malcolmbarrett @brooklynbagel @hfrick

We scheduled a meeting to discuss this on Weds, Nov 17th at 11am PT.  If any of you want to join, give a thumbs up and I will send you the invite.

**Comment by drmowinckels** [comment]
Its a little late for me in the evening, but keep me posted. I'd like to be involved as I rely on the pkg for the new website build.

**Comment by hfrick** [comment]
got the invite :+1:

**Comment by ledell** [comment]
Update: @schloerke is currently working on rewriting the internal query logic and updating the two most useful functions, `get_events()` and `find_groups()`.

**Comment by jromanowska** [comment]
I can help with testing - let me know when.

**Comment by ledell** [comment]
@jromanowska Thank you!  @benubah Please let @jromanowska how she can help, when you're ready.

**Comment by benubah** [comment]
Just to let everyone know... I am working on rewriting the remaining functions. I have working drafts but will send a PR soon so we can start testing.

**Comment by benubah** [comment]
The work (plus testing) is ongoing here: https://github.com/rladies/meetupr/pull/138

**Comment by RickPack** [comment]
Thank you, @benubah!

**Comment by frederikho** [comment]
Great to see that this package is maintained and that the GraphQL support is being added! When can we expect the updates to be merged into the main branch?

**Comment by ledell** [comment]
@frederikho I just merged into master.  Please try it out if you can!  We would really appreciate feedback. Thanks.
