### ISSUE TITLE
topics endpoint?

### ISSUE THREAD

**Issue by maelle** [rladies/meetupr#13]
@hfrick and I wanted to pull all R-Ladies chapters from Meetup with "have R-Ladies as topic" as a definition. https://www.meetup.com/topics/r-ladies/all/

Would you consider adding the function for getting meetups for a topic? 🙏 

Thanks a lot! 💜

**Comment by ledell** [comment]
Sure, we can add this! 
The "topic" API documentation is here: https://www.meetup.com/meetup_api/docs/topics/
But to query by a topic, you must use the [GET /find/groups](https://www.meetup.com/meetup_api/docs/find/groups/) endpoint and pass a `topic_id`, so we will have to add a `topic_id` argument to `find_groups()`:

**Comment by ledell** [comment]
@maelle @hfrick Added this here: https://github.com/rladies/meetupr/pull/18

"R-Ladies" topic id is 1513883.  I still need to add a function that will make it easy to look up topic ids from a search term.
```
meetups <- find_groups(topic_id = 1513883, api_key = api_key)
```

**Comment by maelle** [comment]
👏🎉💪

**Comment by ledell** [comment]
Ready to merge, I think. @maelle @hfrick

**Comment by maelle** [comment]
Cool! Maybe add an example using the new parameter?

**Comment by ledell** [comment]
@maelle Good idea.  I just added one.

**Comment by drmowinckels** [comment]
I'm closing this issue as we have a find_groups function with the new API. 
For this specific issue, also, we will use the pro-network functions, that will locate all groups and events within a pro network :)
