### ISSUE TITLE
Make an RData file to preserve old API results format

### ISSUE THREAD

**Issue by ledell** [rladies/meetupr#135]
Since the Meetup REST API will be shut off any day now, we should save a copy of the output format for all the old functions so that we can have a reference to what the output looked like (as we create the new version of all the files using GraphQL).

Let's run each function and save the tibble for each into an RData file that we can refer to later.

**Comment by benubah** [comment]
Where should we store this file?

**Comment by ledell** [comment]
@benubah Were you able to create these RData files before the old API was cut off?  If so, please send me an email and I will find a place to store them for us.

**Comment by benubah** [comment]
Yes, I did.

**Comment by ledell** [comment]
Here's a public link to the file in case anyone needs it: https://wimlds.box.com/s/lptwpmaweh5dgxnuyvoynumay17n86t3

Later we can consider if we should put this in the repo... (for now I'll close the ticket since the data has been preserved).

**Comment by ledell** [comment]
Thanks @benubah!
