### ISSUE TITLE
Relax group admin constraints in `get_event_attendees()`

### ISSUE THREAD

**Issue by ledell** [rladies/meetupr#22]
There is a [blog post](https://rickpackblog.wordpress.com/2018/02/13/meetup-com-yes-rsvp-graphing-fun-with-httr-package-and-rladies-meetupr/) by [Rick Pack](https://github.com/RickPack) about trying to use the `meetupr::get_event_attendees()` function and he pointed out that this currently requires the user to be an admin of that group.

It looks like he was able to get around that constraint in his [code](https://github.com/RickPack/Meetup_RSVP_Yes/blob/master/Meetup_RSVP_Yes.R) so we should figure out if we can update the `get_event_attendees()` to not require group admin rights.

Here's an example:
```
> past_events <- get_events(urlname = "rladies-nashville", event_status = "past")
> past_events
# A tibble: 9 x 21
         id                                            name
      <chr>                                           <chr>
1 234968855                     R-Ladies Nashville Kickoff!
2 235652800             December Meetup: data.table package
3 235757913              January Meetup: R Resources & Help
4 237055230 February Meetup: RStudio Conference Highlights!
5 237055481                    March Meetup: Intro to Shiny
6 239935025                           An R + Github Journey
7 242098493           Working with Pipes %>% + GIS Tutorial
8 243331077                           Introduction to purrr
9 243331084      Play in the snow, then clean up your mess!
# ... with 19 more variables: created <dttm>, status <chr>,
#   time <dttm>, local_date <date>, local_time <chr>,
#   waitlist_count <int>, yes_rsvp_count <int>, venue_id <int>,
#   venue_name <chr>, venue_lat <dbl>, venue_lon <dbl>,
#   venue_address_1 <chr>, venue_city <chr>, venue_state <chr>,
#   venue_zip <chr>, venue_country <chr>, description <chr>,
#   link <chr>, resource <list>
> get_event_attendees(urlname, event_id = 234968855)
Error in .quick_fetch(api_url = api_url, api_key = api_key, event_status = event_status,  : 
  Bad Request (HTTP 400).
```

We also need to add some tests to check for this type of thing.

**Comment by RickPack** [comment]
I do not know if this can be circumvented. [Meetup](https://www.meetup.com/meetup_api/docs/:urlname/events/:id/attendance/#list) indicates the API method used (Attendance) by `get_event_attendees()` is "Limited for use by administrative members.". Maybe another API will provide all of the values that are needed. I used the restriction-free [RSVPs v2 method](https://www.meetup.com/meetup_api/docs/2/rsvps/) in my [Meetup_RSVP_Yes.R code](https://github.com/RickPack/Meetup_RSVP_Yes)(count and graph "Yes" RSVPs). Thank you all for the great code. I gratefully used your `.date_helper` function.

**Comment by RickPack** [comment]
I am working on adding get_yesrsvps() to my forked version. Thank you, @ledell, for inviting me on Twitter to do a pull-request. https://twitter.com/ledell/status/963601064023883776

**Comment by RickPack** [comment]
I am naming the program `get_event_rsvps.R` to align with your other programs.

**Comment by RickPack** [comment]
I just saw that @brooklynbagel has a pull request for `get_event_rsvps.R` so I will abort my work.

**Comment by ledell** [comment]
Since this seems to be a limitation of the API in v3 (that you can only query this data for your own groups), then we should add an custom error message (inside a `stop()` function) so that the user knows the limitations. We want to replace this:
```
Error in .quick_fetch(api_url = api_url, api_key = api_key, event_status = event_status,  : 
  Bad Request (HTTP 400).
```
With something nicer that tells the user that they can only use this on their own groups.  If we can catch the 400 error inside `.quick_fetch()`, then add something like `stop("You may only query attendee data for groups that you administer.")`, that would be good.

Also the documentation should be updated to indicate this.

If anyone wants to add this functionality, please let us know!

**Comment by RickPack** [comment]
I am happy to work on the stop() message and documentation update. Might you assign this to me?

**Comment by ledell** [comment]
Hi @RickPack, that would be great.  I have invited you to become a "collaborator" on this repo, and after you accept the invitation, I can assign it to you (I can't assign it to you unless you're a collaborator).  Let me know when you've accepted.

**Comment by RickPack** [comment]
I accepted. Thank you for helping me understand how this works!

**Comment by ledell** [comment]
No worries, I didn't realize either until I tried to assign it to you and it wouldn't let me!

**Comment by RickPack** [comment]
Updated in pull request #27. Please note that I had to do manual uploads because of my computer setup, should that cause any misleading indications in Github. I only changed the `Readme` (see bottom point), and then `get_event_attendees.Rd` and `get_event_attendees.R` :

Updated `get_event_attendees` error message to show ""HTTP 400 error encountered. Might you have requested data for which the Meetup API requires that you be the respective group's administrator (e.g., event attendee data)?" [stop function in internals.R]
Accordingly updated documentation
Changed `Readme` get_events function's argument to event_status = "past" because default of "future" was showing 0 records

**Comment by RickPack** [comment]
Use of manual file upload may explain why so many lines appeared to have been changed by my code.  Updated in pull request #28 (used RStudio remote connection to Github).
