### ISSUE TITLE
Use ratelimitr to not get 429 errors?

### ISSUE THREAD

**Issue by maelle** [rladies/meetupr#30]
Poke @kierisi 

[`ratelimitr`](https://github.com/tarakc02/ratelimitr)

The [docs](https://www.meetup.com/meetup_api/) say "You can know your current rate limit status by reading X-RateLimit HTTP headers included in responses. The following table indicates their name and meaning. " so I guess this issue is related to #9. 

I imagine the code would need to make a call at the start of each session to determine what to put in the `ratelimitr` call 🤔

**Comment by kierisi** [comment]
I was able to get around rate limits by using the `slowly` function that Jenny wrote:

```
slowly <- function(f, delay = 0.5) {
  function(...) {
    Sys.sleep(delay)
    f(...)
  }
}
```

wrapping `get_events` in `slowly` and `safely` like so `slowly(safely(get_events)` worked like a dream.

full call: `map(urls2, slowly(safely(get_events)), event_status = c("past", "upcoming"))`

**Comment by maelle** [comment]
That's fantastic! I read it like a potential Daft Punk song.

Now in the package the rate should definitely depend on the headers returned by the API this way it can even be faster (I guess you guessed 0.5?).

This is how it's done in `monkeylearn` where there are two rate limits: https://github.com/ropensci/monkeylearn/blob/02d6df74d50d75bd7d86d9793d746927f126f0a8/R/utils.R#L372

So inside the package code it might be

```r
get_events_unlimited <- current function definition
get_events <- ratelimitr::limit_rate(
  get_events_unlimited,
  ratelimitr::rate(n = blabla, period = otherblabla),
)
```

with blabla and otherblabla derived from the headers (since Meetup docs say that's where the rate limit can be found)?

**Comment by kierisi** [comment]
🎵 slowly 🎵 safely 🎵 get your  🎵data 🎵 

I used the 0.5 as that's what Jenny used, and since it worked I didn't see a need to change it 😂 

Being able to pull in from the API headers would be great! I wasn't sure how to access that information from within the `meetupr` package though.

**Comment by missaugustina** [comment]
"These responses indicate that you are making requests too quickly. If you receive one of these errors, you should adjust the frequency of your requests by adding a pause between them."

I'm actually testing this out on some code I want to convert to use MeetupR. I think you'll still hit a limit if you make too many requests in the time interval, even with a pause. Maybe MeetupR can check the X-Limit header and issue a warning if it's getting close.

The headers are returned in the .quick_fetch() function
https://github.com/rladies/meetupr/blob/master/R/internals.R#L26

But they are dropped in .fetch_results()
https://github.com/rladies/meetupr/blob/master/R/internals.R#L73

Based on what else I see there, I would probably write a "rate-limit" helper function and decide what functionality you think makes sense. You can get to the headers from within .fetch_results() https://github.com/rladies/meetupr/blob/master/R/internals.R#L44 so the helper function could be called within there.

**Comment by maelle** [comment]
Duplicate of #9
