### ISSUE TITLE
Add Mocking to Unit tests so they don't make For Realz api calls

### ISSUE THREAD

**Issue by missaugustina** [rladies/meetupr#31]
The unit tests are currently making "IRL" api calls which can result in failures in the event of no network access. Additionally, these tests may result in errors beyond the scope of what is actually being tested. Ultimately, at least for these tests, we just want to know if our library code is working, we don't care about the api key or httr.

That said, other end-to-end continuous integration tests should be developed that do call the API from TravisCi but that's beyond the scope of this issue. I'll file it as a second one and mention this one to link it.

**Comment by missaugustina** [comment]
~~I found a package called "mockery" is this the appropriate one to use or do people have other ones they prefer?~~

Looks like testthat() has a "with_mock" function - https://www.rdocumentation.org/packages/testthat/versions/2.0.0/topics/with_mock

**Comment by ledell** [comment]
@missaugustina So these tests are in addition to the real ones, or are you proposing that we replace the live tests with mock tests?  It looks like you have opened another issue to add live tests back in? https://github.com/rladies/meetupr/issues/33

**Comment by missaugustina** [comment]
@ledell yes, I'm proposing that the tests that are currently live be replaced with the mocks. The existing tests are disabled in TravisCI and they failed for me when I ran them locally.

And yes, I'm proposing in #33 that we add integration tests to make sure our stuff still works with the Meetup API. I would see these just running when a PR was merged and shouldn't be too fragile.

Does that sound ok? Or would you rather I did the work on #33 before this one could be merged?

Note that this one enables the tests on TravisCI, so we get test coverage with every change TravisCI builds.

**Comment by missaugustina** [comment]
Looks like my change got merged! We should make sure we get some tests in per #33 to monitor meetup api compatibility.
