### ISSUE TITLE
api_key argument does not default to NULL in get_boards

### ISSUE THREAD

**Issue by pr130** [rladies/meetupr#41]
I set my API key using `Sys.setenv(MEETUP_KEY="mykey")`. I can then use all functions without specifying the `api_key` argument because all functions set it to NULL as default and `.fetch_results` will then check for NULL and draw it from the Sys env. 

The `get_boards` function does not specify NULL as default for api_key, hence resulting in a missing argument error. 

---

``` r
library(meetupr)
get_boards(urlname = "rladies-san-francisco")
#> Error in .fetch_results(api_method, api_key): argument "api_key" is missing, with no default
```

**Comment by ledell** [comment]
@friep Thank you!!

**Comment by ledell** [comment]
Merged the PR fixing this.

**Comment by pr130** [comment]
Nice :) happy to have been able to contribute! :)
