### ISSUE TITLE
Add find_topics() function

### ISSUE THREAD

**Issue by ledell** [rladies/meetupr#44]
Add a [`find_topics()`](https://www.meetup.com/meetup_api/docs/topics/) function so you can look up the topic ids that match a search term.  You can find topic ids by querying here: https://secure.meetup.com/meetup_api/console/?path=/find/topics

This is related to: https://github.com/rladies/meetupr/issues/13

**Comment by ledell** [comment]
Should be something like this:

```
find_topics <- function(query = NULL, api_key = NULL) {
  api_method <- "find/topics"
  res <- .fetch_results(api_method = api_method,
                        api_key = api_key,
                        query = query)
  tibble::tibble(
    # change all these to be the fields that it actually returns:
    # look them up here or look at what you see in `res`
    # https://www.meetup.com/meetup_api/docs/find/topics/
    id = purrr::map_int(res, "id"),
    name = purrr::map_chr(res, "name"),
    resource = res
  )
}
```

The fields look like this (let's include all besides `lang`):
```[[1]]
[[1]]$id
[1] 1513883

[[1]]$name
[1] "R-Ladies"

[[1]]$urlkey
[1] "r-ladies"

[[1]]$group_count
[1] 140

[[1]]$member_count
[1] 39953

[[1]]$description
[1] "Find out what's happening in R-Ladies Meetup groups around the world and start meeting up with the ones near you."

[[1]]$lang
[1] "en_US"
```
End result:
```topics <- find_topics(query = "R-Ladies")```

**Comment by ledell** [comment]
Hey @priyankagagneja it's been a while since we chatted about this task.  I can't remember where we left off, but I am curious if you're still interested in working on this?  Otherwise, I'll re-add the "help wanted" label to this to see if someone can finish it.

**Comment by drmowinckels** [comment]
I'm not sure this task really is needed anymore? I'm closing it for now.
