### ISSUE TITLE
Changes to the API

### ISSUE THREAD

**Issue by malcolmbarrett** [rladies/meetupr#50]
I received an email this morning from Meetup about changing their API from key-based to OAuth-based on August 15, 2019. It looks like a substantial change that may affect the package: https://www.meetup.com/meetup_api/auth/?utm_medium=email&utm_source=transactional&utm_campaign=api_update&utm_content=en_06142019#oauth2

It also appears that OAuth accounts are free until August 15 but will require a pro account after that :/

**Comment by malcolmbarrett** [comment]
@ledell just posted this to #51 so I'm going to close this

**Comment by ledell** [comment]
Thanks @malcolmbarrett.
