### ISSUE TITLE
Add meetupr to the list of official clients on meetup.com 

### ISSUE THREAD

**Issue by ledell** [rladies/meetupr#52]
We need to make a PR to add it here: https://github.com/meetup/api/blob/master/clients.md

**Comment by GregSutcliffe** [comment]
Looks like it's already there? It appears to have been added a year ago:

https://github.com/meetup/api/blob/master/clients.md#r

**Comment by gdequeiroz** [comment]
I added it 2 years ago: https://github.com/rladies/meetupr/issues/10 🙃

**Comment by ledell** [comment]
I didn't realize it was already on the list!  Closing ticket...
