### ISSUE TITLE
get_event_attendees

### ISSUE THREAD

**Issue by orchid00** [rladies/meetupr#58]
Hi, 

Something might have changed (at some point)

This file
https://github.com/rladies/meetupr/blob/master/R/get_event_attendees.R
Is looking for the word "attendance", but now the word should be "attendees"

You can check https://www.meetup.com/CHAPTERNAME/events/EVENTID/attendees/

**Comment by ledell** [comment]
@orchid00 Did you mean to close this?  Is it still an issue?

**Comment by orchid00** [comment]
Not an issue
