### ISSUE TITLE
Deprecate API key methods

### ISSUE THREAD

**Issue by ledell** [rladies/meetupr#59]
Now that we [added OAuth support](https://github.com/rladies/meetupr/issues/51) and the API key authentication scheme is no longer functional, we can deprecate the API key methods.

Current plan is to remove the `api_key` argument and add `...` to swallow any `api_key` args that appear in old/outdated scripts.

**Comment by jennybc** [comment]
I think -- but I'm not sure -- that it might be easier to just eliminate the API key stuff now. If that seems to be true, do I have encouragement to pursue that / make such a PR?

**Comment by ledell** [comment]
@jennybc Yeah, there’s no use to the api key code anymore.  Feel free to get rid of it!
