### ISSUE TITLE
get_events() throws an error when no events found for a query

### ISSUE THREAD

**Issue by missaugustina** [rladies/meetupr#62]
Via Athanasia 

> Hi folks! I’m playing around with the meetupr package we have on github.
> I was wondering whether the`get_events` function should throw an error when no events are found for a query? Is it really an error if there are no upcoming events? Should it not rather be a warning? 

I am looking to see if our code is doing this or if its something from the Meetup API.

**Comment by ledell** [comment]
@missaugustina No, it should definitely not throw an error.  Are they using the latest version of the package?  If so, can you (or they) post a reproducible example?  Thanks! :-)

**Comment by missaugustina** [comment]
Confirmed this is in our code 
https://github.com/rladies/meetupr/blob/master/R/internals.R#L31

**Comment by missaugustina** [comment]
Yes @ledell i'm pushing an update to the unit test where I repro'ed

**Comment by missaugustina** [comment]
I need the test to catch the httr::stop(), figuring how to do that with testthat rn.

<img width="1440" alt="Screen Shot 2019-09-04 at 2 03 38 PM" src="https://user-images.githubusercontent.com/101733/64291406-edf80880-cf1c-11e9-9012-ce16985afdba.png">

**Comment by missaugustina** [comment]
PR up but need coverage for other methods to make sure they don't barf.

- [x] get_boards.R
- [x] get_event_attendees.R
- [x] get_event_comments.R
- [x] get_event_rsvps.R
- [x] get_members.R

**Comment by missaugustina** [comment]
I have to get Meetup auth set up on my end to do a full end-to-end test. If someone who has it set up could test this branch in the meantime I would be most pleased :)
