### ISSUE TITLE
Why is a secret api key publicly checked into the repo?

### ISSUE THREAD

**Issue by missaugustina** [rladies/meetupr#64]
https://github.com/rladies/meetupr/blob/master/R/zzz.R#L6

This stuff doesn't go into a public repo, major security risk. Someone could spoof you for data mining & it may violate Meetup's TOS. 

People need to add their own api keys to their .Renviron files. If this isn't in the README or other instructions then in addition to removing that file, add an example to show ppl how.

**Comment by missaugustina** [comment]
Needs to be rebased out of history too so ppl can't access the old file.

**Comment by ledell** [comment]
@missaugustina Normally, this is not something to go on GitHub, but it's required as a dummy key to get the package to work for users who don't have their own key.  We had a discussion about here and talked to other package authors with a similar predicament and this was decided to be the best option: https://github.com/rladies/meetupr/pull/54
