### ISSUE TITLE
Make a pkgdown webpage hosted on GitHub

### ISSUE THREAD

**Issue by ledell** [rladies/meetupr#72]
It would be nice to have a simple [pkgdown](https://pkgdown.r-lib.org/) website.  We could host it at: https://rladies.github.io/meetupr

**Comment by malcolmbarrett** [comment]
I'd be happy to work on a PR for this! I've had a great experience with meetupr in managing our meetup data and website, so it'd be great to contribute a little.

The `r-lib/actions` [GitHub Actions script](https://github.com/r-lib/actions/tree/master/examples#build-pkgdown-site) for deploying pkgdown sites to GitHub Pages has worked very well for me

**Comment by ledell** [comment]
@malcolmbarrett That would be fantastic!  We would greatly welcome your contribution.
