### ISSUE TITLE
Build failing on Travis CI

### ISSUE THREAD

**Issue by ledell** [rladies/meetupr#75]
The build has been failing for 6 months: https://travis-ci.org/github/rladies/meetupr/branches

I don't see any issues with the [DESCRIPTION file](https://github.com/rladies/meetupr/blob/master/DESCRIPTION#L48) though.. 

```
Building with: R CMD build 
0.26s$ R CMD build  .
* checking for file ‘./DESCRIPTION’ ... OK
* preparing ‘meetupr’:
* checking DESCRIPTION meta-information ... ERROR

Malformed Depends or Suggests or Imports or Enhances field.

Offending entries:
  tibble
knitr

Entries must be names of packages optionally followed by '<=' or '>=',
white space, and a valid version number in parentheses.
See section 'The DESCRIPTION file' in the 'Writing R Extensions'
manual.

The command "R CMD build  ." failed and exited with 1 during .

Your build has been stopped.
```

**Comment by malcolmbarrett** [comment]
Maybe I can't see all the build errors, but isn't the one from 6 months ago referring to the `DESCRIPTION` file in the `light-refresh-tests` branch? The file on that branch is mangled and produces the same error when I replicate: https://github.com/rladies/meetupr/blob/86e22735868139d5d407fd0ab5c9e3e2789cc944/DESCRIPTION#L46-L51

But it looks to my eye like that branch is related to a merged PR and that the current `DESCRIPTION` is fine/passing?

**Comment by ledell** [comment]
@malcolmbarrett I merged some PRs and made some updates in the past day and it seems to have cleared things up on Travis.  So I am going to close this ticket!  Thanks for checking though.
