### ISSUE TITLE
bug for  find_groups(topic_id = 1513883)

### ISSUE THREAD

**Issue by maelle** [rladies/meetupr#86]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](http://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---

Brief description of the problem

```r
# insert reprex here
```

**Comment by ledell** [comment]
Hey @maelle is this a real issue?  Looks like a possible copy/paste error?  Thanks. :-)

**Comment by maelle** [comment]
it wasn't, I had gotten an error but can't reproduce it so :woman_shrugging:
