### ISSUE TITLE
Make verbose controllable by an option

### ISSUE THREAD

**Issue by maelle** [rladies/meetupr#94]
cc @Athanasiamo -- does it sound like a good idea?

**Comment by drmowinckels** [comment]
yes! Im my growing PR for pro #92 there is a commit for it

**Comment by maelle** [comment]
in your PR it is an argument, not an option yet or am I missing something?

I mean that the default value of the argument would be something with `getOption("meetupr.verbose")`

**Comment by drmowinckels** [comment]
ah right, sorry I misunderstood. I'm not so used to working with options rather than arguments, so I'm not sure what would be the best, tbh. I'll let you decide.

**Comment by maelle** [comment]
or, we could make FALSE the default, or make it TRUE by default when the session is interactive. :thinking:

**Comment by drmowinckels** [comment]
what I like with arguments is that is more straight forward for the user how to silence it if they want, options can be a little less accessible.

**Comment by maelle** [comment]
I'd still have both, since the argument would read the option, you could still use the argument.

**Comment by drmowinckels** [comment]
ok, that sounds like a nice idea

**Comment by maelle** [comment]
I'll wait until your PR is merged since it introduces the verbose argument.

I think its default value should be `verbose = getOption("meetupr.verbose", rlang::is_interactive())`

* this way one can still use the argument
* one can toggle the value via a project/user level Rprofile
* the default is still TRUE in interactive session.
* `rlang::is_interactive()` can be mocked in tests so easier to test we supress messages when we should.
